global using System.Reflection;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using TaskTracker.Application.Interfaces.Context;
global using TaskTracker.Domain.Entities;
global using TaskTracker.Infrastructure.Interceptors;